### ISSUE TITLE
Add binary corruption test

### ISSUE THREAD

**Issue by jqr** [DocRaptor/docraptor-python#5]
It's easy for generated clients to return accidentally utf8 encoded data, which ends up corrupting PDF/XLS/XLSX files. Let's add a test to ensure this can never happen.

**Comment by AlexOverbeck** [comment]
Our current tests should cover most encoding issues. The [file test](https://github.com/DocRaptor/docraptor-python/blob/master/test/file.py) is a good example where we write the response in binary mode. When you write a binary file in Python it will [default to strict mode](https://docs.python.org/3.5/library/functions.html#open) and throw an error if we try to write a "non-bytes like object".

##### Example
```python
with open("/tmp/docraptor-python.pdf", "wb") as f:
  f.write('some crazy wizbiz😬')
```
_results in:_
```
TypeError: a bytes-like object is required, not 'str'
```
